### ISSUE TITLE
come up with list of ingredients that can be randomized with a few modifiers

### ISSUE THREAD

**Issue by djblooky** [SyFySkyE/WitchesBrew#1]

**Comment by djstagen** [comment]
Ingredients List
- Mandrake roots
- Bat wings
- Sugar
- Pumpkin puree
- Rum
- Rat tail
- Crushed mana crystal powder
- Frog legs
- Bird brain
- Griffin feather
- Vanilla extract
(more will be added if needed)

**Comment by SyFySkyE** [comment]
• Blood
• Tears
• Cursed souls
• Eyeballs
• Baby shoes, never worn
• Pumpkin spice
(Some of these can be recipe's themselves, which also get randomized. Also we can start a list of adjectives and nouns and randomize those as well)

**Comment by djstagen** [comment]
Recipe List (so far)

- Pumkin bat latte
- Mandrake Vanilla tea 
- RRR (Triple R for Rancid Rat Rum)
-Feathered Vanilla Brain latte

**Comment by VinylKnight** [comment]
I wanted to add a few more ingredients to the mix.

- Toad spit 
- Wyvern nails
- Boar hairs
- Octopus ink
- Beetle Mandibles
- Mantis Thorax
- Possum eyes
- Spider webs
- Brown sugar
