### ISSUE TITLE
narrow down list of recipes and corresponding ingredients for prototype

### ISSUE THREAD

**Issue by djblooky** [SyFySkyE/WitchesBrew#18]
- [x] 3 recipes

**Comment by VinylKnight** [comment]
Current Recipes used for the prototype
 - Sweet Tears - Tears, Eyeballs, Vanilla
- Pumpkin Mice Latte - Rat Tail, Rat Tail, Pumpkin Spice
- Witch's Brew - Frog Legs, Snails, Baby Shoes

Google Docs for Recipes and Ingredients - [https://drive.google.com/file/d/1QGTyzUFPghjj-Hcah70DxF_BN7J-M_fy/view?usp=sharing](url)
