### ISSUE TITLE
basic title screen

### ISSUE THREAD

**Issue by djblooky** [SyFySkyE/WitchesBrew#31]

**Comment by VinylKnight** [comment]
![Screenshot (55)](https://user-images.githubusercontent.com/33336283/96194368-ce992080-0f0f-11eb-9e2c-f67097fc701c.png)
![Screenshot (54)](https://user-images.githubusercontent.com/33336283/96194369-cf31b700-0f0f-11eb-9ebf-7c5447f86874.png)
 current basic title menu with functionality
