### ISSUE TITLE
pick out in-game fonts

### ISSUE THREAD

**Issue by djblooky** [SyFySkyE/WitchesBrew#43]
- [ ] look at google fonts sans serif

**Comment by djstagen** [comment]
https://www.dafont.com/hallowitchz.font
https://www.dafont.com/spooky-light.font
https://www.dafont.com/witched.font

**Comment by djstagen** [comment]
https://fonts.google.com/specimen/Fira+Sans?category=Sans+Serif

https://fonts.google.com/specimen/Rubik?category=Sans+Serif
